export const MASTER_DATA_CUSTOMERS              = 'MASTER_DATA_CUSTOMERS'
export const MASTER_DATA_CUSTOMERS_LOADING      = 'MASTER_DATA_CUSTOMERS_LOADING'
export const MASTER_DATA_SERVICES               = 'MASTER_DATA_SERVICES'
export const MASTER_DATA_SERVICES_LOADING       = 'MASTER_DATA_SERVICES_LOADING'